version: '3.4'

services:
  livesteaming:
    image: livesteaming
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3008:3008
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
